#!/usr/bin/env python3
"""Generate the tobyOS TEST certificate authority (HTTP/3 slice 4h).

Emits, into this directory:
  test_ca.pem / test_ca_key.pem     -- a self-signed RSA-2048 test CA
  test_leaf.pem / test_leaf_key.pem -- an RSA-2048 leaf for `tobyos.test`
                                       signed by the CA
  test_chain.pem                    -- leaf + CA (what a test server serves)
and, into third_party/bearssl/:
  test_ca_anchor.inc                -- the CA as a BearSSL trust anchor
                                       (same layout `brssl ta` emits)

The anchor is compiled into the kernel ONLY under -DTLS_TEST_CA (see
src/tls_trust.c); production builds never trust this CA. The private
keys are committed on purpose -- this is test material for verifying
the QUIC/TLS handshake against a locally-run server, nothing else.

Requires: pip install cryptography
"""
import datetime
import os

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

HERE = os.path.dirname(os.path.abspath(__file__))
BEARSSL = os.path.normpath(os.path.join(HERE, "..", "..", "third_party", "bearssl"))


def write_pem(path, data):
    with open(path, "wb") as f:
        f.write(data)
    print("wrote", path)


def c_bytes(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
        lines.append("\t" + chunk + ("," if i + 12 < len(data) else ""))
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    now = datetime.datetime.now(datetime.timezone.utc)

    ca_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    ca_name = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "tobyOS"),
        x509.NameAttribute(NameOID.COMMON_NAME, "tobyOS test CA"),
    ])
    ca_cert = (
        x509.CertificateBuilder()
        .subject_name(ca_name).issuer_name(ca_name)
        .public_key(ca_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=3650))
        .add_extension(x509.BasicConstraints(ca=True, path_length=1), critical=True)
        .add_extension(x509.KeyUsage(
            digital_signature=False, content_commitment=False,
            key_encipherment=False, data_encipherment=False,
            key_agreement=False, key_cert_sign=True, crl_sign=True,
            encipher_only=False, decipher_only=False), critical=True)
        .sign(ca_key, hashes.SHA256())
    )

    leaf_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    leaf_name = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "tobyOS"),
        x509.NameAttribute(NameOID.COMMON_NAME, "tobyos.test"),
    ])
    leaf_cert = (
        x509.CertificateBuilder()
        .subject_name(leaf_name).issuer_name(ca_name)
        .public_key(leaf_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=825))
        .add_extension(x509.SubjectAlternativeName(
            [x509.DNSName("tobyos.test")]), critical=False)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None),
                       critical=True)
        .sign(ca_key, hashes.SHA256())
    )

    enc = serialization.Encoding.PEM
    nokey = serialization.NoEncryption()
    pk8 = serialization.PrivateFormat.PKCS8
    ca_pem = ca_cert.public_bytes(enc)
    leaf_pem = leaf_cert.public_bytes(enc)
    write_pem(os.path.join(HERE, "test_ca.pem"), ca_pem)
    write_pem(os.path.join(HERE, "test_ca_key.pem"),
              ca_key.private_bytes(enc, pk8, nokey))
    write_pem(os.path.join(HERE, "test_leaf.pem"), leaf_pem)
    write_pem(os.path.join(HERE, "test_leaf_key.pem"),
              leaf_key.private_bytes(enc, pk8, nokey))
    write_pem(os.path.join(HERE, "test_chain.pem"), leaf_pem + ca_pem)

    # BearSSL trust anchor: the DER-encoded subject DN + the raw RSA
    # public key (n without leading zero, e), flags = BR_X509_TA_CA.
    dn = ca_cert.subject.public_bytes()
    pub = ca_key.public_key().public_numbers()
    n = pub.n.to_bytes((pub.n.bit_length() + 7) // 8, "big")
    e = pub.e.to_bytes((pub.e.bit_length() + 7) // 8, "big")

    inc = (
        "/* tobyOS TEST CA as a BearSSL trust anchor -- generated by\n"
        " * tests/quic-ca/make_test_ca.py. Compiled into the kernel ONLY\n"
        " * under -DTLS_TEST_CA (src/tls_trust.c); never trusted by a\n"
        " * production build. */\n\n"
        + c_bytes("TEST_TA0_DN", dn) + "\n"
        + c_bytes("TEST_TA0_RSA_N", n) + "\n"
        + c_bytes("TEST_TA0_RSA_E", e) + "\n"
        + "static const br_x509_trust_anchor TEST_TAs[] = {\n"
        + "\t{\n"
        + "\t\t{ (unsigned char *)TEST_TA0_DN, sizeof TEST_TA0_DN },\n"
        + "\t\tBR_X509_TA_CA,\n"
        + "\t\t{\n"
        + "\t\t\tBR_KEYTYPE_RSA,\n"
        + "\t\t\t{ .rsa = {\n"
        + "\t\t\t\t(unsigned char *)TEST_TA0_RSA_N, sizeof TEST_TA0_RSA_N,\n"
        + "\t\t\t\t(unsigned char *)TEST_TA0_RSA_E, sizeof TEST_TA0_RSA_E,\n"
        + "\t\t\t} }\n"
        + "\t\t}\n"
        + "\t}\n"
        + "};\n\n"
        + "#define TEST_TAs_NUM   1\n"
    )
    out = os.path.join(BEARSSL, "test_ca_anchor.inc")
    with open(out, "w", newline="\n") as f:
        f.write(inc)
    print("wrote", out)


if __name__ == "__main__":
    main()
