/* tls_trust.c -- Mozilla root CA trust anchors for BearSSL X.509
 * validation (stage 13H). The array is generated by BearSSL's own
 * `brssl ta cacert.pem` from the curl.se Mozilla CA bundle (121 roots,
 * RSA + EC public keys); see third_party/bearssl/trust_anchors.inc.
 * Exposed to src/tls.c via tls_trust_anchors().
 *
 * Under -DTLS_TEST_CA (HTTP/3 slice 4h verification builds ONLY) the
 * tobyOS test CA (tests/quic-ca/, third_party/bearssl/
 * test_ca_anchor.inc) is appended so a locally-run QUIC/TLS server
 * presenting a cert chained to it validates. Production builds never
 * define TLS_TEST_CA and never trust it. */

#include <bearssl.h>

#include "../third_party/bearssl/trust_anchors.inc"   /* TAs[], TAs_NUM */

#ifdef TLS_TEST_CA
#include "../third_party/bearssl/test_ca_anchor.inc"  /* TEST_TAs[], TEST_TAs_NUM */

static br_x509_trust_anchor g_all_tas[TAs_NUM + TEST_TAs_NUM];
static int g_all_init;

const br_x509_trust_anchor *tls_trust_anchors(size_t *count) {
    if (!g_all_init) {
        for (size_t i = 0; i < TAs_NUM; i++) g_all_tas[i] = TAs[i];
        for (size_t i = 0; i < TEST_TAs_NUM; i++)
            g_all_tas[TAs_NUM + i] = TEST_TAs[i];
        g_all_init = 1;
    }
    *count = TAs_NUM + TEST_TAs_NUM;
    return g_all_tas;
}

#else

const br_x509_trust_anchor *tls_trust_anchors(size_t *count) {
    *count = TAs_NUM;
    return TAs;
}

#endif
