/* tls_trust.c -- Mozilla root CA trust anchors for BearSSL X.509
 * validation (stage 13H). The array is generated by BearSSL's own
 * `brssl ta cacert.pem` from the curl.se Mozilla CA bundle (121 roots,
 * RSA + EC public keys); see third_party/bearssl/trust_anchors.inc.
 * Exposed to src/tls.c via tls_trust_anchors(). */

#include <bearssl.h>

#include "../third_party/bearssl/trust_anchors.inc"   /* TAs[], TAs_NUM */

const br_x509_trust_anchor *tls_trust_anchors(size_t *count) {
    *count = TAs_NUM;
    return TAs;
}
