/* toby/notify.hpp -- OPTIONAL header-only C++ convenience wrapper
 * around <tobyos_notify.h>. SDK consumers may use either the C API or
 * this wrapper; nothing in the SDK requires C++.
 *
 * No new code is generated by this header beyond inline trampolines:
 * each method forwards directly to the C function and the compiler
 * inlines them away in -O2 builds.
 */

#ifndef TOBY_NOTIFY_HPP
#define TOBY_NOTIFY_HPP

#include <tobyos_notify.h>

namespace toby {

/* Light wrapper that turns the four C calls into a namespaced API.
 * Stateless -- no constructor, no member data; this is just a place
 * to hang nicer names without resorting to a free namespace pollution
 * macro. */
struct notify {
    static int post(unsigned urgency, const char *title, const char *body = nullptr) {
        return ::toby_notify_post(urgency, title, body);
    }

    static long list(struct abi_notification *out, unsigned cap) {
        return ::toby_notify_list(out, cap);
    }

    static int dismiss(unsigned id = 0) {
        return ::toby_notify_dismiss(id);
    }

    static long unread() {
        return ::toby_notify_unread();
    }

    /* Convenience shortcuts that fix the urgency at the call site. */
    static int info(const char *title, const char *body = nullptr) {
        return ::toby_notify_post(TOBY_NOTIFY_INFO, title, body);
    }
    static int warn(const char *title, const char *body = nullptr) {
        return ::toby_notify_post(TOBY_NOTIFY_WARN, title, body);
    }
    static int err(const char *title, const char *body = nullptr) {
        return ::toby_notify_post(TOBY_NOTIFY_ERR, title, body);
    }
};

}  /* namespace toby */

#endif /* TOBY_NOTIFY_HPP */
